name: Build & Commit

on: [repository_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

    - name: Checkout Main
      uses: actions/checkout@v2
      with:
        path: Main

    - name: Checkout Remote
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.repository }}
        token: ${{ secrets.ACCESS_TOKEN }}
        path: Remote

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Remote Project
      id: build-remote-project
      if: github.event.action == 'commit-build'
      env:
        SOLUTION_FILE_PATH: ./Remote
        BUILD_CONFIGURATION: Release
        BUILD_PLATFORM: "x86"
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform=${{env.BUILD_PLATFORM}}

    - name: Commit dll
      if: steps.build-remote-project.conclusion == 'success'
      run: |
        mv -force ./Remote/Release/ml_fixes.dll ./Main
        cd Main
        git config user.email ${{ secrets.USER_EMAIL }}
        git config user.name ${{ secrets.USER }}
        git add ml_fixes.dll
        git commit -m "Build #${{ github.run_number }} - Built dll from '${{ github.event.client_payload.repository }}'"
        git push
